import  com.example.springbootdrools.request.DepositRequest;

rule "外包召回1"
    when
        depositObject : DepositRequest( loanType=="Fixed" && durationInYear >= 1 && durationInYear < 2 && age < 60);
    then
        depositObject.setInterestRate("5%");
end;

rule "外包召回2"
    when
        depositObject : DepositRequest( loanType=="Recurring" && durationInYear >= 1 && durationInYear < 2 && age < 60);
    then
        depositObject.setInterestRate("3%");
end;
